version: 2.1

defaults: &defaults
  working_directory: ~/design-system
  docker:
    - image: circleci/node:10-browsers
  environment:
    TZ: '/usr/share/zoneinfo/America/Los_Angeles'

aliases:
  # Circle related commands
  - &restore-cache
    keys:
      # Find a cache corresponding to this specific package.json checksum
      # when this file is changed, this key will fail
      - design-system--
      - design-system-
      # Find the most recent cache used from any branch
      - design-system-
  - &save-cache
    key: design-system--
    paths:
      - ~/.cache/yarn
      - node_modules
  # Yarn commands
  - &yarn
    name: Install Dependencies
    command: yarn install --frozen-lockfile --non-interactive
  # - &lint
  #   name: Lint
  #   command: yarn lint
  - &build
    name: Build
    command: yarn build

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *yarn
      - save_cache: *save-cache
      - persist_to_workspace:
          root: .
          paths:
            - .

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/design-system
      - run: *build
      - persist_to_workspace:
          root: .
          paths:
            - .

  documentation:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/design-system
      - run:
          name: Build Storybook
          command: yarn build:storybook
      - run:
          name: Build Playroom
          command: yarn build:playroom
      - store_artifacts:
          path: ./out
          destination: documentation
      - run:
          name: Post Link to storybook + playroom
          command: node ./.circleci/post-build-url.js

  pr-check:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/design-system
      - run:
          name: PR Version Check
          command: yarn auto pr-check --url $CIRCLE_BUILD_URL

  unit-tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/design-system
      - run:
          name: Unit Tests
          command: yarn test

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/design-system
      - run:
          name: Lint
          command: yarn lint

  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/design-system
      - run: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: Release
          command: yarn release

  size:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/design-system
      - run:
          name: Check component bundle sizes
          command: SIZE_TABLE=`yarn --silent size --ci` && npx auto comment --message "$SIZE_TABLE" --context bundle

  a11y:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/design-system
      - run:
          name: Check component accessibility
          command: node ./.circleci/proof-a11y.js

  integration:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/design-system
      - run:
          name: Run integrations tests
          command: node ./.circleci/proof.js

workflows:
  version: 2
  build_and_test:
    jobs:
      - install

      - build:
          requires:
            - install

      - pr-check:
          requires:
            - build
          filters:
            branches:
              ignore:
                - master

      - unit-tests:
          requires:
            - build

      - lint:
          requires:
            - build

      - documentation:
          requires:
            - unit-tests
            - lint

      - release:
          requires:
            - documentation
          filters:
            branches:
              only:
                - master

      - size:
          requires:
            - documentation
          filters:
            branches:
              ignore:
                - master

      - a11y:
          requires:
            - documentation
          filters:
            branches:
              ignore:
                - master

      - integration:
          requires:
            - documentation
          filters:
            branches:
              ignore:
                - master
